/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMovieIndexRouteImport } from './routes/_app/movie/index'
import { Route as AppMovieMovieIdRouteImport } from './routes/_app/movie/$movieId'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppPersonPersonIdRouteImport } from './routes/_app/person/$personId'
import { Route as AppSearchIndexRouteImport } from './routes/_app/search/index'
import { Route as AppTvIndexRouteImport } from './routes/_app/tv/index'
import { Route as AppTvTvIdRouteRouteImport } from './routes/_app/tv/$tvId/route'
import { Route as AppWatchlistIndexRouteImport } from './routes/_app/watchlist/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/sign-up/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTvTvIdIndexRouteImport } from './routes/_app/tv/$tvId/index'
import { Route as AppTvTvIdSeasonSeasonNumberRouteRouteImport } from './routes/_app/tv/$tvId/season/$seasonNumber/route'
import { Route as AppTvTvIdSeasonSeasonNumberIndexRouteImport } from './routes/_app/tv/$tvId/season/$seasonNumber/index'
import { Route as AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRouteImport } from './routes/_app/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMovieIndexRoute = AppMovieIndexRouteImport.update({
  id: '/movie/',
  path: '/movie/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMovieMovieIdRoute = AppMovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPersonPersonIdRoute = AppPersonPersonIdRouteImport.update({
  id: '/person/$personId',
  path: '/person/$personId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTvIndexRoute = AppTvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTvTvIdRouteRoute = AppTvTvIdRouteRouteImport.update({
  id: '/tv/$tvId',
  path: '/tv/$tvId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWatchlistIndexRoute = AppWatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTvTvIdIndexRoute = AppTvTvIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTvTvIdRouteRoute,
} as any)
const AppTvTvIdSeasonSeasonNumberRouteRoute =
  AppTvTvIdSeasonSeasonNumberRouteRouteImport.update({
    id: '/season/$seasonNumber',
    path: '/season/$seasonNumber',
    getParentRoute: () => AppTvTvIdRouteRoute,
  } as any)
const AppTvTvIdSeasonSeasonNumberIndexRoute =
  AppTvTvIdSeasonSeasonNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTvTvIdSeasonSeasonNumberRouteRoute,
  } as any)
const AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute =
  AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRouteImport.update({
    id: '/episode/$episodeNumber',
    path: '/episode/$episodeNumber',
    getParentRoute: () => AppTvTvIdSeasonSeasonNumberRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/tv/$tvId': typeof AppTvTvIdRouteRouteWithChildren
  '/movie/$movieId': typeof AppMovieMovieIdRoute
  '/person/$personId': typeof AppPersonPersonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/movie/': typeof AppMovieIndexRoute
  '/people/': typeof AppPeopleIndexRoute
  '/search/': typeof AppSearchIndexRoute
  '/tv/': typeof AppTvIndexRoute
  '/watchlist/': typeof AppWatchlistIndexRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/sign-up/': typeof AuthSignUpIndexRoute
  '/tv/$tvId/': typeof AppTvTvIdIndexRoute
  '/tv/$tvId/season/$seasonNumber': typeof AppTvTvIdSeasonSeasonNumberRouteRouteWithChildren
  '/tv/$tvId/season/$seasonNumber/': typeof AppTvTvIdSeasonSeasonNumberIndexRoute
  '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber': typeof AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/movie/$movieId': typeof AppMovieMovieIdRoute
  '/person/$personId': typeof AppPersonPersonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/movie': typeof AppMovieIndexRoute
  '/people': typeof AppPeopleIndexRoute
  '/search': typeof AppSearchIndexRoute
  '/tv': typeof AppTvIndexRoute
  '/watchlist': typeof AppWatchlistIndexRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/sign-up': typeof AuthSignUpIndexRoute
  '/tv/$tvId': typeof AppTvTvIdIndexRoute
  '/tv/$tvId/season/$seasonNumber': typeof AppTvTvIdSeasonSeasonNumberIndexRoute
  '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber': typeof AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/tv/$tvId': typeof AppTvTvIdRouteRouteWithChildren
  '/_app/movie/$movieId': typeof AppMovieMovieIdRoute
  '/_app/person/$personId': typeof AppPersonPersonIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/movie/': typeof AppMovieIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/search/': typeof AppSearchIndexRoute
  '/_app/tv/': typeof AppTvIndexRoute
  '/_app/watchlist/': typeof AppWatchlistIndexRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_app/tv/$tvId/': typeof AppTvTvIdIndexRoute
  '/_app/tv/$tvId/season/$seasonNumber': typeof AppTvTvIdSeasonSeasonNumberRouteRouteWithChildren
  '/_app/tv/$tvId/season/$seasonNumber/': typeof AppTvTvIdSeasonSeasonNumberIndexRoute
  '/_app/tv/$tvId/season/$seasonNumber/episode/$episodeNumber': typeof AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tv/$tvId'
    | '/movie/$movieId'
    | '/person/$personId'
    | '/api/auth/$'
    | '/movie/'
    | '/people/'
    | '/search/'
    | '/tv/'
    | '/watchlist/'
    | '/sign-in/'
    | '/sign-up/'
    | '/tv/$tvId/'
    | '/tv/$tvId/season/$seasonNumber'
    | '/tv/$tvId/season/$seasonNumber/'
    | '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movie/$movieId'
    | '/person/$personId'
    | '/api/auth/$'
    | '/movie'
    | '/people'
    | '/search'
    | '/tv'
    | '/watchlist'
    | '/sign-in'
    | '/sign-up'
    | '/tv/$tvId'
    | '/tv/$tvId/season/$seasonNumber'
    | '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/'
    | '/_app/tv/$tvId'
    | '/_app/movie/$movieId'
    | '/_app/person/$personId'
    | '/api/auth/$'
    | '/_app/movie/'
    | '/_app/people/'
    | '/_app/search/'
    | '/_app/tv/'
    | '/_app/watchlist/'
    | '/_auth/sign-in/'
    | '/_auth/sign-up/'
    | '/_app/tv/$tvId/'
    | '/_app/tv/$tvId/season/$seasonNumber'
    | '/_app/tv/$tvId/season/$seasonNumber/'
    | '/_app/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/movie/': {
      id: '/_app/movie/'
      path: '/movie'
      fullPath: '/movie/'
      preLoaderRoute: typeof AppMovieIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/movie/$movieId': {
      id: '/_app/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof AppMovieMovieIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/person/$personId': {
      id: '/_app/person/$personId'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof AppPersonPersonIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/search/': {
      id: '/_app/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tv/': {
      id: '/_app/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof AppTvIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tv/$tvId': {
      id: '/_app/tv/$tvId'
      path: '/tv/$tvId'
      fullPath: '/tv/$tvId'
      preLoaderRoute: typeof AppTvTvIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/watchlist/': {
      id: '/_app/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof AppWatchlistIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up/': {
      id: '/_auth/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tv/$tvId/': {
      id: '/_app/tv/$tvId/'
      path: '/'
      fullPath: '/tv/$tvId/'
      preLoaderRoute: typeof AppTvTvIdIndexRouteImport
      parentRoute: typeof AppTvTvIdRouteRoute
    }
    '/_app/tv/$tvId/season/$seasonNumber': {
      id: '/_app/tv/$tvId/season/$seasonNumber'
      path: '/season/$seasonNumber'
      fullPath: '/tv/$tvId/season/$seasonNumber'
      preLoaderRoute: typeof AppTvTvIdSeasonSeasonNumberRouteRouteImport
      parentRoute: typeof AppTvTvIdRouteRoute
    }
    '/_app/tv/$tvId/season/$seasonNumber/': {
      id: '/_app/tv/$tvId/season/$seasonNumber/'
      path: '/'
      fullPath: '/tv/$tvId/season/$seasonNumber/'
      preLoaderRoute: typeof AppTvTvIdSeasonSeasonNumberIndexRouteImport
      parentRoute: typeof AppTvTvIdSeasonSeasonNumberRouteRoute
    }
    '/_app/tv/$tvId/season/$seasonNumber/episode/$episodeNumber': {
      id: '/_app/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'
      path: '/episode/$episodeNumber'
      fullPath: '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'
      preLoaderRoute: typeof AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRouteImport
      parentRoute: typeof AppTvTvIdSeasonSeasonNumberRouteRoute
    }
  }
}

interface AppTvTvIdSeasonSeasonNumberRouteRouteChildren {
  AppTvTvIdSeasonSeasonNumberIndexRoute: typeof AppTvTvIdSeasonSeasonNumberIndexRoute
  AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute: typeof AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute
}

const AppTvTvIdSeasonSeasonNumberRouteRouteChildren: AppTvTvIdSeasonSeasonNumberRouteRouteChildren =
  {
    AppTvTvIdSeasonSeasonNumberIndexRoute:
      AppTvTvIdSeasonSeasonNumberIndexRoute,
    AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute:
      AppTvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute,
  }

const AppTvTvIdSeasonSeasonNumberRouteRouteWithChildren =
  AppTvTvIdSeasonSeasonNumberRouteRoute._addFileChildren(
    AppTvTvIdSeasonSeasonNumberRouteRouteChildren,
  )

interface AppTvTvIdRouteRouteChildren {
  AppTvTvIdIndexRoute: typeof AppTvTvIdIndexRoute
  AppTvTvIdSeasonSeasonNumberRouteRoute: typeof AppTvTvIdSeasonSeasonNumberRouteRouteWithChildren
}

const AppTvTvIdRouteRouteChildren: AppTvTvIdRouteRouteChildren = {
  AppTvTvIdIndexRoute: AppTvTvIdIndexRoute,
  AppTvTvIdSeasonSeasonNumberRouteRoute:
    AppTvTvIdSeasonSeasonNumberRouteRouteWithChildren,
}

const AppTvTvIdRouteRouteWithChildren = AppTvTvIdRouteRoute._addFileChildren(
  AppTvTvIdRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppTvTvIdRouteRoute: typeof AppTvTvIdRouteRouteWithChildren
  AppMovieMovieIdRoute: typeof AppMovieMovieIdRoute
  AppPersonPersonIdRoute: typeof AppPersonPersonIdRoute
  AppMovieIndexRoute: typeof AppMovieIndexRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
  AppTvIndexRoute: typeof AppTvIndexRoute
  AppWatchlistIndexRoute: typeof AppWatchlistIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppTvTvIdRouteRoute: AppTvTvIdRouteRouteWithChildren,
  AppMovieMovieIdRoute: AppMovieMovieIdRoute,
  AppPersonPersonIdRoute: AppPersonPersonIdRoute,
  AppMovieIndexRoute: AppMovieIndexRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
  AppTvIndexRoute: AppTvIndexRoute,
  AppWatchlistIndexRoute: AppWatchlistIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
